### ISSUE TITLE
Panic state in player listener

### ISSUE THREAD

**Issue by thejeancarton** [SpotifyXP/SpotifyXP#23] opened 2024-02-11 19:30 UTC
```
[java.lang.UnknownError: PanicState in PlayerListener] com.spotifyxp.listeners.PlayerListener.onPanicState(PlayerListener.java:206)
com.spotifyxp.deps.xyz.gianlu.librespot.player.Player$EventsDispatcher.lambda$panicState$14(Player.java:1232)
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
java.base/java.lang.Thread.run(Thread.java:1589)
```

**Comment by werwolf2303** [comment] 2024-02-18 03:59
Sorry for the late response. I was feeling worse again... mentally.

When does this happen?

**Comment by lesar8** [comment] 2024-02-18 17:36
I got this error too, randomly but occasionally, after auto or manual switch to different track. It also comes along with this error:

`[java.util.concurrent.RejectedExecutionException: Task com.spotifyxp.deps.xyz.gianlu.librespot.audio.cdn.CdnManager$Streamer$InternalStream$$Lambda$185/22406510@8cb47 rejected from java.util.concurrent.ThreadPoolExecutor@195298b[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = *]] `

Worse, sometimes SpotifyXP show this message "Can't get default token" or so everytime I open a track and I need to relaunch it to play music.

**Comment by werwolf2303** [comment] 2024-02-19 09:01
I should test SpotifyXP more often on Windows XP instead of MacOS. I will inform you when there is a fix available for these issues. The only thing that's confusing me is the "Couldn't get default token", this should not happen. Weird but I will try to find out the cause

**Comment by werwolf2303** [comment] 2024-02-20 12:24
Can you post the exception you got on the "Cannot get default token". That would be very helpful

**Comment by lesar8** [comment] 2024-02-20 21:56
> Can you post the exception you got on the "Cannot get default token". That would be very helpful

It's kinda impossible to click to the errors dialog because the message keep poping up times lol.. I tried, sorry..

![abc](https://github.com/SpotifyXP/SpotifyXP/assets/133925958/e8a7444a-1ffd-4282-96a7-3c3640212d60)

**Comment by werwolf2303** [comment] 2024-02-21 05:05
Please open cmd and execute this inside the folder where the SpotifyXP.jar is: "java -jar SpotifyXP.jar --setup-complete --debug"

**Comment by lesar8** [comment] 2024-02-22 23:06
Got no luck today, I've been testing for more than 5 hourse but the "Couldn't get default token" doesnt trigger yet.. (it's rarely triggered). On the other hand, i got the debug log for "Panic state in player listener" and "[java.lang.IndexOutOfBoundsException Index 0, Size 0]" error.

[PanicState in PlayerListener.txt](https://github.com/SpotifyXP/SpotifyXP/files/14380196/PanicState.in.PlayerListener.txt)
[[java.lang.IndexOutOfBoundsException Index 0, Size 0].txt](https://github.com/SpotifyXP/SpotifyXP/files/14380195/java.lang.IndexOutOfBoundsException.Index.0.Size.0.txt)

The "IndexOutOfBoundsException" is a nasty error that I forgot to tell you. Song will stop playing and relaunch required. I will do the test tomorrow and hope for the error trigger.

**Comment by werwolf2303** [comment] 2024-02-23 04:52
Ok thanks I will try to fix them

**Comment by werwolf2303** [comment] 2024-03-05 06:17
Does the issue still persist in the newest nightly?

**Comment by lesar8** [comment] 2024-03-06 06:01
> Does the issue still persist in the newest nightly?

Unfortunately it's still throwing the same error as mentioned above. Here is a debug log, hope it help.
[[java.lang.IndexOutOfBoundsException Index 0, Size 0] .txt](https://github.com/SpotifyXP/SpotifyXP/files/14505257/java.lang.IndexOutOfBoundsException.Index.0.Size.0.txt)
[PanicState in PlayerListener.txt](https://github.com/SpotifyXP/SpotifyXP/files/14505258/PanicState.in.PlayerListener.txt)

**Comment by werwolf2303** [comment] 2024-03-06 06:13
There are a lot of "socket timed out" errors. What type of internet do you have(fiber optic, DSL, VDSL, Dial-Up)? What internet card do you have in this device?

**Comment by lesar8** [comment] 2024-03-06 06:28
> There are a lot of "socket timed out" errors. What type of internet do you have(fiber optic, DSL, VDSL, ADSL, Dial-Up)? What internet card do you have in this device?

I using adsl connection and onboard Realtek ethernet. When I switch to 4G connection (via USB), the same error is still happens so I don't think it's related to internet type and device.

**Comment by werwolf2303** [comment] 2024-03-06 06:31
Ok so then it isn't your internet type... Maybe it'ss that your connection is unstable. Can you please check that with: "speedtest.net" please give me the results afterwards

**Comment by lesar8** [comment] 2024-03-06 06:37
> Ok so then it isn't your internet type... Maybe it's that your connection is unstable. Can you check that with: "speedtest.net" please give me the results afterwards

Here it is: https://www.speedtest.net/result/15974846970

My internet is very stable (i have wired connection), i don't have any problems at all watching videos or browsing or even downloading

**Comment by werwolf2303** [comment] 2024-03-06 06:39
Ok same internet type and speed as me. So it is definitely not your internet... I have to look more into this "socket timed out" thing.

**Comment by lesar8** [comment] 2024-03-06 06:52
> Ok same internet type and speed as me. So it is definitely not your internet... I have to look more into this "socket timed out" thing.

This "IndexOutOfBoundsException" error is very odd, everytimes I play song it's just throw an error on "Errors" dialog and force me to re-launch SpotifyXP. This feel like something related to SpotifyXP itself, but not Spotify server.

**Comment by werwolf2303** [comment] 2024-03-06 06:54
I only require a user to restart SpotifyXP if it's a critical non recoverable error

**Comment by werwolf2303** [comment] 2024-03-06 06:55
When I have time I will add a "Continue? SpotifyXP is maybe unstable

**Comment by lesar8** [comment] 2024-03-06 07:22
> I only require a user to restart SpotifyXP if it's a critical non recoverable error

Well sorry for wrong choice of word, i mean the "IndexOutOfBoundsException" error prevent track to be play so I need to re-launch SpotifyXP.

**Comment by werwolf2303** [comment] 2024-03-06 07:23
I will research this and come up with a fix

**Comment by werwolf2303** [comment] 2024-04-12 05:22
Please check if this is fixed in the newest nightly build

**Comment by lesar8** [comment] 2024-04-12 11:59
Unfortunately I'm still getting the 'Panic state' and 'IndexOutOfBoundsException' errors in the newest nightly build.

**Comment by werwolf2303** [comment] 2024-04-12 15:26
I found out why the fix wasn't working :) I didn't upload it.... LOL

**Comment by werwolf2303** [comment] 2024-04-15 16:47
Please check if this error still happens

**Comment by lesar8** [comment] 2024-04-16 10:43
Well.. it's still happening and also comes along with a new error "Java.Net.SocketException: Socket closed".

Screenshot and debug log attached.
![error](https://github.com/SpotifyXP/SpotifyXP/assets/133925958/174dc0e2-6a28-4f08-a27e-80fdbb8025f2)

[Debug Log.txt](https://github.com/SpotifyXP/SpotifyXP/files/14995588/Log.txt)

**Comment by FlorianisonGitHub** [comment] 2024-05-09 23:30
Will SpotifyXP get any better?

**Comment by werwolf2303** [comment] 2024-05-10 09:53
The underlying library that I'm using was apparently never designed to run in the backend so I had to modify a lot of it to get to the state that SpotifyXP is today. I'm still fixing issues if I find any. So to answer your question: Yes SpotifyXP will become better but this will take it's time

**Comment by werwolf2303** [comment] 2024-08-19 19:00
!!!This project is DEAD!!! For updates: https://github.com/SpotifyXP/SpotifyXP/issues/51. I will leave the repository open for someone to fix it

**Closed by werwolf2303** 2024-08-19 19:00 UTC
