### ISSUE TITLE
SpotifyXP stuck on "creating api..."

### ISSUE THREAD

**Issue by HIXOXIH** [SpotifyXP/SpotifyXP#56] opened 2024-09-21 00:35 UTC
Just like the first time I used SpotifyXP, after the installation process, nothing else happens. It doesn't create the icon on the desktop and the login screen doesn't appear. But then I used the same method I used the previous time to get it running (--setup-complete --debug). Then it opens but gets stuck on the "creating api..." screen.
I do what the message says for the new login method (I open Spotify on my smartphone and tap on devices) but nothing happens and SpotifyXP doesn't appear on Spotify devices. Help me!

**Note:I,m using SpotifyXP 2.0.3 and my account is premium**

**Comment by werwolf2303** [comment] 2024-09-23 18:30
Please give me the full system specs including language and username. This way I can check if the icon problem has anything to do with special characters. 

Does your network allow local network connections? 
Are the pc and the phone on the same network?

**Comment by werwolf2303** [comment] 2024-09-23 18:31
I will investigate the creating api issue when I finished the switch to Android

**Comment by HIXOXIH** [comment] 2024-09-23 22:40
My language is Brazilian Portuguese. My Spotify username is h4v0ck. My PC and smartphone are on the same network and I could find SPOTIFYXP on Spotify on my phone before.

**Comment by werwolf2303** [comment] 2024-09-26 14:32
When did it stop working?

**Comment by HIXOXIH** [comment] 2024-09-27 02:01
It stopped when you said that the project had died due to a login
modification made by the Spotify team. But I did the new method that you
discovered and that brought the project back to life.It turns out that I'm
not able to get out of the "creating api..." screen even after following
the steps to log in. In fact, I don't think I'll ever be able to because of
this new version that I downloaded at your request (2.0.3) The login screen
did not appear for me. Therefore, it cannot appear on my smartphone's
Spotify devices because for this to happen, I must first log in to
SpotifyXP using the same account that I am using on Spotify. Only after
this will SpotifyXP appear in the list of Spotify devices on my cell phone.

Em qui, 26 de set de 2024 11:33, werwolf2303 ***@***.***>
escreveu:

**Comment by werwolf2303** [comment] 2024-09-27 18:43
Hmm. I see what I can do about that tomorrow

**Comment by werwolf2303** [comment] 2024-09-30 12:46
I don't know why it doesn't work. But I will continue investigating

**Comment by werwolf2303** [comment] 2024-10-01 13:31
I use the Spotify connect protocol. It's normally for embedded devices such as Sonos speakers. It broadcasts itself onto the network

**Comment by HIXOXIH** [comment] 2024-10-02 01:23
Well... then I have no idea why it doesn't work. Do you have any more recent version I could try?

**Comment by Jri-creator** [comment] 2024-10-02 02:43
I wonder... What happens if somebody tries to pair with Spotify-compatible devices, such as Sonos Speakers, with a free plan. Would it produce the same result [Upgrade to Premium] or will it be different? If it's different, is there a way to mock the device with SpotifyXP so that it works on the free plan?

**Comment by werwolf2303** [comment] 2024-10-02 08:06
You can actually pair some speakers with a free plan but only the speakers that have a newer Spotify library version

**Comment by werwolf2303** [comment] 2024-10-04 12:17
The thing is it worked when I implemented it. so I don't know what happened

**Comment by HIXOXIH** [comment] 2024-10-04 12:27
😔😔😔

**Comment by werwolf2303** [comment] 2024-10-04 12:39
It's broadcasting on 0.0.0.0 so it should show up in the entire network. As a workaround:

1. Log in on a modern machine via a local Spotify install
2. Copy the credentials.json from the users home directory/SpotifyXP to the same path on the other machine
3. Should log in

**Comment by HIXOXIH** [comment] 2024-10-05 00:26
I did a search for "*.json" across my SSD and no "credentials.json" was found.

**Comment by werwolf2303** [comment] 2024-10-05 08:08
It should be in the SpotifyXP directory after you authenticated

**Comment by HIXOXIH** [comment] 2024-10-06 02:56
But when does this authentication occur? Because for me, the login screen doesn't even appear. It just stays on the "creating api..."

**Comment by werwolf2303** [comment] 2024-10-06 12:06
Are you using a nightly version?

**Comment by HIXOXIH** [comment] 2024-10-07 02:24
Yes, I am!

Em dom, 6 de out de 2024 09:07, werwolf2303 ***@***.***>
escreveu:

**Comment by werwolf2303** [comment] 2024-10-08 17:45
It's very hard to diagnose something that I can't replicate. Please record a video of everything with the cmd debug. Command: java -jar SpotifyXP.jar --setup-complete --debug

**Comment by HIXOXIH** [comment] 2024-10-13 19:18
Here is the video:

https://github.com/user-attachments/assets/fc0947f2-5854-4e37-93b8-80747831bd03

**Comment by werwolf2303** [comment] 2024-10-14 12:22
Please execute this command in cmd

**Comment by HIXOXIH** [comment] 2024-10-15 01:57
![cmd](https://github.com/user-attachments/assets/26c633ce-a733-4fb4-a77c-1dd787233817)

**Comment by HIXOXIH** [comment] 2024-10-15 02:15
![debug](https://github.com/user-attachments/assets/565c64df-ab26-4ef0-bab3-57a98bfb216c)

**Comment by werwolf2303** [comment] 2024-10-15 09:03
I think I know what the problem is. I will create a fix today

**Comment by werwolf2303** [comment] 2024-10-17 21:18
Please check if the firewall in Windows XP is enabled. In my case firewalld (Linux firewall) blocked SpotifyXP. As soon as I disabled my firewall it started working

**Comment by HIXOXIH** [comment] 2024-10-17 22:33
My firewall has been disabled since I installed Windows XP. I thought you
were going to release a new version with the fix for the problem you
identified in the debug.

Em qui, 17 de out de 2024 18:18, werwolf2303 ***@***.***>
escreveu:

**Comment by werwolf2303** [comment] 2024-10-18 08:39
Please try the newest nightly and send me a photo of the debug output

**Comment by HIXOXIH** [comment] 2024-10-20 01:41
IT'S WORKING NOW 😃😃😃😃😃😃 I'll make the debug video later if you still want it. 
My question now is: Will it continue to work after I stop being a premium user?

**Comment by Jri-creator** [comment] 2024-10-20 03:06
I suppose it may not, but you are the one who is reporting the progress. Let us know if it still works after you switch back to Spotify Free. I think it won't, though.

**Comment by werwolf2303** [comment] 2024-10-20 16:15
When someone provides me the eSDK. I can make zeroconf work with free accounts

**Comment by Jri-creator** [comment] 2024-10-20 17:43
Anything here you can work with?
https://spotify.github.io/#java

**Comment by werwolf2303** [comment] 2024-10-20 18:07
No I need this library: https://developer.spotify.com/documentation/commercial-hardware/implementation/reference/3.199

**Comment by HIXOXIH** [comment] 2024-10-21 16:35
Is authentication only required the first time you open SpotifyXP after installation? Or will you need to authenticate using another device every time you open SpotifyXP?

**Comment by HIXOXIH** [comment] 2024-10-21 17:44
I tested it here and it opens without having to do the authentication procedure again.
Now what is happening is an error message every time I change to the next track. It doesn't cause any problems with playback, but I noticed that the name of the current track and the cover are still the same as the first track.

**Comment by HIXOXIH** [comment] 2024-10-21 17:45
![error](https://github.com/user-attachments/assets/114c6a28-06e5-42a2-8acc-cc032cfcce90)

**Comment by werwolf2303** [comment] 2024-10-21 18:22
Please open one of the exceptions so that I can see the stacktrace

**Comment by werwolf2303** [comment] 2024-10-22 00:37
Great but also not great. Keep me updated if the issue happens again

**Comment by HIXOXIH** [comment] 2024-10-30 00:57
Hey. Where is the file that makes SpotifyXP no longer need the authentication that is done the first time (opening it and then going to Spotify devices and tapping SpotifyXP)?
I tried to find where SpotifyXP is installed (documents and settings/SpotifyXP) And although there are some files there, none of them are what I'm looking for. My goal is to keep a copy of it.And if I need to reinstall SpotifyXP, I won't need to have a premium account to find SpotifyXP on devices.

**Comment by werwolf2303** [comment] 2024-10-30 11:54
There should be a credentials.json in appdata/SpotifyXP

**Comment by HIXOXIH** [comment] 2024-10-31 02:08
I searched the entire unit where the system is installed and found nothing like that.The only .json I found that is inside the SpotifyXP folder is InjectorStore.json 
If this file you mentioned exists, then why can't I find it? :/

**Comment by HIXOXIH** [comment] 2024-10-31 02:23
I tried searching the entire drive and found nothing. But then I noticed that the search was excluding hidden files and folders. I just re-searched and included the hidden ones and found it 😃 Thank U

**Comment by werwolf2303** [comment] 2024-11-12 20:38
I will close this issue because it's a while since someone reported this issue

**Closed by werwolf2303** 2024-11-12 20:38 UTC

**Comment by Midnight-Rambler-72** [comment] 2024-11-14 14:25
Is Bluetooth required for passing the authentication?
I'm asking, because even though I'm using latest nightly version I don't get any loging window like in HIXOXIH video that asks for connecting on the modern device. 

> Here is the video:
> 20241013_155801_001_001.mp4

**Comment by Midnight-Rambler-72** [comment] 2024-11-14 19:04
It's the video from Oct 13th message in this thread.

**Comment by werwolf2303** [comment] 2024-11-14 19:10
Ok. You don't need Bluetooth because authentication works via your local network. Does SpotifyXP appear in Spotify?

**Comment by Midnight-Rambler-72** [comment] 2024-11-14 19:48
No it doesn't.

**Comment by werwolf2303** [comment] 2024-11-15 15:32
@Midnight-Rambler-72  The log says you are already logged in. You can delete the credentials.json to reset the login, the file is in: HOME/SpotifyXP

**Comment by Midnight-Rambler-72** [comment] 2024-11-15 20:08
Thanks, it worked! You're the best!

**Comment by HIXOXIH** [comment] 2024-12-17 17:55
Just stopping by to say that even though apps cancel my premium subscription, SpotifyXP continues to open and work perfectly.👍🏻🙂

**Comment by Jri-creator** [comment] 2024-12-26 16:44
Interesting 🤔 I'll have to try and see if that does work. If it does, then that could help free users, since they get many premium deals that last for a bit.
